In [1]:
import torch.nn as nn
import torch
import torch.nn.functional as F

In [2]:
m = torch.randn(16,10,10)

In [9]:
m.shape

torch.Size([10, 10])

In [10]:
m = torch.randn(10,10)
m

tensor([[ 3.1447e-02,  3.2668e-01, -1.7085e+00, -5.4144e-01, -4.4171e-01,
         -2.7244e+00,  1.9379e+00,  1.9653e-01,  9.2765e-01, -9.1062e-01],
        [ 7.2113e-01,  1.2584e-01,  1.3145e+00, -4.4236e-01,  6.0245e-01,
         -7.2190e-01,  2.0908e+00, -6.5826e-01,  1.8812e+00,  5.3028e-01],
        [-9.8089e-01, -1.9077e-02, -2.2262e-01, -1.5045e+00,  2.4048e-01,
         -7.5032e-01, -5.8930e-02,  1.2326e+00,  2.6630e-01,  2.7602e+00],
        [ 2.1198e-01,  6.0433e-01, -2.0433e-02, -1.1413e+00,  3.1655e-01,
         -2.0304e+00,  1.3585e+00, -9.3737e-01, -1.1473e+00, -2.7243e-01],
        [-1.1220e+00,  4.6036e-01, -7.9252e-01, -2.1815e+00, -5.2034e-01,
         -3.1954e-01, -1.8479e-01,  7.8500e-01,  5.8837e-01,  4.2441e-01],
        [-1.3408e+00, -9.0267e-01, -8.7640e-01,  2.0388e-01, -5.8022e-01,
         -4.6303e-01, -6.2919e-04, -6.8968e-02,  1.5976e-01,  9.4712e-01],
        [-1.0584e+00,  7.2376e-01, -4.4445e-01,  3.1836e-01,  6.2859e-01,
         -1.7672e+00,  1.9939e-0

In [11]:
torch.eig(m)

torch.return_types.eig(
eigenvalues=tensor([[ 1.9819,  2.4940],
        [ 1.9819, -2.4940],
        [ 2.8347,  0.0000],
        [-3.0739,  0.8954],
        [-3.0739, -0.8954],
        [-1.2038,  2.0603],
        [-1.2038, -2.0603],
        [ 0.2939,  0.6124],
        [ 0.2939, -0.6124],
        [-0.2552,  0.0000]]),
eigenvectors=tensor([]))

In [13]:
torch.rand(10,10).mean()

tensor(0.5130)

In [15]:
torch.randn(10,10)

tensor([[-4.8176e-02,  7.6771e-01, -1.6432e+00, -1.9178e-01,  8.5711e-01,
          1.2240e+00, -1.5911e-01,  1.9872e-01,  9.1373e-01, -8.7305e-01],
        [-9.8386e-02,  1.2465e+00,  6.5991e-01, -2.5145e-01,  7.4687e-01,
         -2.1940e-01, -1.1304e+00, -9.3520e-01, -1.5594e+00, -1.5585e+00],
        [ 3.5543e-01,  1.1585e+00, -1.0377e+00,  1.8529e+00,  6.5053e-01,
         -2.1278e+00, -1.1634e+00,  1.4021e+00,  6.7093e-01, -5.3817e-01],
        [-5.7099e-01,  8.2360e-02, -1.3845e+00, -3.0416e-01, -7.1347e-01,
         -4.2155e-01,  9.1945e-01, -2.3024e+00, -3.2827e-02,  8.8343e-01],
        [-1.7183e+00,  1.9819e+00, -9.2287e-02, -7.2772e-01,  4.2364e-02,
         -1.0414e+00,  4.9867e-01,  1.3450e+00, -4.2339e-02,  4.9512e-01],
        [ 1.2654e+00,  4.6807e-02,  2.8336e-01,  1.8065e+00,  9.8196e-01,
         -1.1619e+00,  1.1469e+00, -9.9717e-01,  1.2640e-01,  5.0108e-01],
        [-1.4556e+00,  1.2922e+00,  1.9016e+00,  3.5858e-02, -1.0105e-01,
         -8.2714e-01,  6.2036e-0

In [31]:
torch.randint(low=-5, high=50, size=(3,3))

tensor([[36, 40, 32],
        [-1, 37, 26],
        [35, -2, -5]])

In [32]:
torch.randperm(10)

tensor([3, 9, 5, 7, 8, 6, 0, 1, 4, 2])

In [33]:
torch.randperm(5)

tensor([3, 0, 4, 1, 2])

In [34]:
torch.randperm(10)

tensor([5, 3, 2, 6, 1, 7, 4, 8, 0, 9])